import { useState } from 'react';
import { api } from '../api';
import { C, FONT } from '../constants';
import { Megaphone, Search, Send, Sparkles } from 'lucide-react';

export default function SmartCampaignsPage() {
  const [item, setItem] = useState('');
  const [audience, setAudience] = useState(null);
  const [loadingAudience, setLoadingAudience] = useState(false);
  const [message, setMessage] = useState('');
  const [generating, setGenerating] = useState(false);
  const [sending, setSending] = useState(false);
  const [sendResult, setSendResult] = useState(null);

  const fetchAudience = async () => {
    if (!item) return;
    setLoadingAudience(true);
    try {
      const res = await api.meenzyCampaignAudience(item);
      setAudience(res);
      setSendResult(null);
    } catch (err) {
      console.error(err);
      alert('Failed to fetch audience');
    } finally {
      setLoadingAudience(false);
    }
  };

  const generateAI = async () => {
    if (!item) return;
    setGenerating(true);
    try {
      const res = await api.meenzyCampaignGenerate(item);
      setMessage(res.message || '');
    } catch (err) {
      console.error(err);
      alert('Failed to generate AI message');
    } finally {
      setGenerating(false);
    }
  };

  const sendCampaign = async () => {
    if (!audience || !audience.phones || audience.phones.length === 0) return;
    if (!message) return alert("Message is empty!");
    if (!confirm(`Are you sure you want to send this to ${audience.audienceSize} customers?`)) return;

    setSending(true);
    try {
      const res = await api.meenzyCampaignSend(audience.phones, message);
      setSendResult(res);
    } catch (err) {
      console.error(err);
      alert('Failed to send campaign');
    } finally {
      setSending(false);
    }
  };

  return (
    <div style={{ padding: '24px 32px', fontFamily: FONT, background: C.pageBg, minHeight: '100%' }}>
      <h1 style={{ fontSize: 24, fontWeight: 700, margin: '0 0 8px 0', color: C.text, display: 'flex', alignItems: 'center', gap: 12 }}>
        <Megaphone color={C.primary} size={28} />
        AI Smart Campaigns
      </h1>
      <p style={{ margin: '0 0 32px 0', color: C.textMuted, fontSize: 14 }}>
        Target past buyers with hyper-personalized WhatsApp messages generated by AI.
      </p>

      <div style={{ display: 'flex', gap: 24 }}>
        <div style={{ flex: 1, background: '#fff', padding: 24, borderRadius: 12, border: `1px solid ${C.border}` }}>
          <h2 style={{ margin: '0 0 16px 0', fontSize: 16, color: C.text }}>1. Select Fresh Catch Target</h2>
          <div style={{ display: 'flex', gap: 12, marginBottom: 24 }}>
            <input 
              style={{ flex: 1, padding: '10px 14px', borderRadius: 8, border: `1px solid ${C.border}`, fontSize: 14, outline: 'none' }} 
              placeholder="e.g. Seer Fish, Prawn, Sardine" 
              value={item} 
              onChange={e => setItem(e.target.value)} 
            />
            <button 
              onClick={fetchAudience}
              disabled={loadingAudience || !item}
              style={{ background: C.primary, color: '#fff', border: 'none', borderRadius: 8, padding: '0 16px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8, opacity: (loadingAudience || !item) ? 0.6 : 1 }}
            >
              <Search size={16} />
              Find Buyers
            </button>
          </div>

          {audience && (
            <div style={{ padding: 16, background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 8, color: '#166534', marginBottom: 24 }}>
              <strong>Audience Found:</strong> {audience.audienceSize} past buyers of {item}.
            </div>
          )}

          <h2 style={{ margin: '0 0 16px 0', fontSize: 16, color: C.text, opacity: audience ? 1 : 0.4 }}>2. Generate Message</h2>
          <button 
            onClick={generateAI}
            disabled={!audience || generating}
            style={{ width: '100%', background: '#fff', border: `1px solid ${C.border}`, color: C.text, borderRadius: 8, padding: '12px', fontWeight: 600, cursor: audience ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 16, opacity: audience ? 1 : 0.4 }}
          >
            <Sparkles size={16} color="#8b5cf6" />
            {generating ? 'Generating via OpenRouter...' : 'Auto-Write with AI'}
          </button>

          <textarea 
            style={{ width: '100%', height: 120, padding: 16, borderRadius: 8, border: `1px solid ${C.border}`, fontSize: 14, outline: 'none', resize: 'vertical', fontFamily: 'inherit', boxSizing: 'border-box' }}
            placeholder="Your message will appear here..."
            value={message}
            onChange={e => setMessage(e.target.value)}
            disabled={!audience}
          />
        </div>

        <div style={{ flex: 1, background: '#fff', padding: 24, borderRadius: 12, border: `1px solid ${C.border}`, display: 'flex', flexDirection: 'column' }}>
          <h2 style={{ margin: '0 0 16px 0', fontSize: 16, color: C.text }}>3. Launch Campaign</h2>
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', gap: 16, opacity: (audience && message) ? 1 : 0.4 }}>
            <div style={{ textAlign: 'center', color: C.textMuted, fontSize: 14 }}>
              This will send {audience ? audience.audienceSize : 0} WhatsApp messages.<br/>
              Messages are trickled out automatically to avoid Meta rate limits.
            </div>
            
            <button 
              onClick={sendCampaign}
              disabled={!audience || !message || sending}
              style={{ width: '100%', background: C.primary, color: '#fff', border: 'none', borderRadius: 8, padding: '16px', fontSize: 16, fontWeight: 600, cursor: (audience && message) ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 12 }}
            >
              <Send size={20} />
              {sending ? 'Sending...' : `Send to ${audience ? audience.audienceSize : 0} Customers`}
            </button>

            {sendResult && (
              <div style={{ marginTop: 16, padding: 12, background: '#dcfce7', color: '#166534', borderRadius: 8, textAlign: 'center', width: '100%' }}>
                ✅ Campaign Launched! Queued {sendResult.queued} messages.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
